/* Generated by Yosys 0.28+12 (git sha1 4251d37f4, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "bidcounter.v:1.1-10.10" *)
module bidcounter(count, clk, ctrl, reset);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* src = "bidcounter.v:7.24-7.31|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire _09_;
  (* src = "bidcounter.v:7.24-7.31|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _10_;
  (* src = "bidcounter.v:7.24-7.31|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _11_;
  (* src = "bidcounter.v:7.24-7.31|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _12_;
  (* src = "bidcounter.v:3.19-3.24" *)
  wire _13_;
  (* src = "bidcounter.v:3.19-3.24" *)
  wire _14_;
  (* src = "bidcounter.v:3.19-3.24" *)
  wire _15_;
  (* src = "bidcounter.v:3.19-3.24" *)
  wire _16_;
  (* src = "bidcounter.v:2.18-2.22" *)
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  (* force_downto = 32'd1 *)
  (* src = "bidcounter.v:7.24-7.31|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  (* unused_bits = "1 2 3" *)
  wire [3:0] _25_;
  (* force_downto = 32'd1 *)
  (* src = "bidcounter.v:7.24-7.31|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _26_;
  (* src = "bidcounter.v:2.8-2.11" *)
  input clk;
  wire clk;
  (* src = "bidcounter.v:3.19-3.24" *)
  output [3:0] count;
  reg [3:0] count;
  (* src = "bidcounter.v:2.18-2.22" *)
  input ctrl;
  wire ctrl;
  (* src = "bidcounter.v:2.12-2.17" *)
  input reset;
  wire reset;
  sky130_fd_sc_hd__clkinv_1 _27_ (
    .A(_13_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nand2b_1 _28_ (
    .A_N(_17_),
    .B(_14_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__xor2_1 _29_ (
    .A(_14_),
    .B(_17_),
    .X(_19_)
  );
  sky130_fd_sc_hd__xnor2_1 _30_ (
    .A(_13_),
    .B(_19_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__o21ai_0 _31_ (
    .A1(_09_),
    .A2(_19_),
    .B1(_18_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__xor2_1 _32_ (
    .A(_17_),
    .B(_15_),
    .X(_21_)
  );
  sky130_fd_sc_hd__xnor2_1 _33_ (
    .A(_20_),
    .B(_21_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nand4_1 _34_ (
    .A(_13_),
    .B(_14_),
    .C(_17_),
    .D(_15_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__or4_1 _35_ (
    .A(_13_),
    .B(_14_),
    .C(_17_),
    .D(_15_),
    .X(_23_)
  );
  sky130_fd_sc_hd__nand2_1 _36_ (
    .A(_22_),
    .B(_23_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__xor2_1 _37_ (
    .A(_16_),
    .B(_24_),
    .X(_12_)
  );
  (* src = "bidcounter.v:4.2-9.5" *)
  always @(posedge clk)
    if (reset) count[0] <= 1'h0;
    else count[0] <= _25_[0];
  (* src = "bidcounter.v:4.2-9.5" *)
  always @(posedge clk)
    if (reset) count[1] <= 1'h0;
    else count[1] <= _26_[1];
  (* src = "bidcounter.v:4.2-9.5" *)
  always @(posedge clk)
    if (reset) count[2] <= 1'h0;
    else count[2] <= _26_[2];
  (* src = "bidcounter.v:4.2-9.5" *)
  always @(posedge clk)
    if (reset) count[3] <= 1'h0;
    else count[3] <= _26_[3];
  assign _26_[0] = _25_[0];
  assign _13_ = count[0];
  assign _25_[0] = _09_;
  assign _14_ = count[1];
  assign _17_ = ctrl;
  assign _26_[1] = _10_;
  assign _15_ = count[2];
  assign _26_[2] = _11_;
  assign _16_ = count[3];
  assign _26_[3] = _12_;
endmodule
