/* Generated by Yosys 0.28+12 (git sha1 4251d37f4, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module bidcounter(count, clk, ctrl, reset);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire [3:0] _29_;
  wire [3:0] _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  input clk;
  wire clk;
  output [3:0] count;
  wire [3:0] count;
  input ctrl;
  wire ctrl;
  input reset;
  wire reset;
  sky130_fd_sc_hd__clkinv_1 _35_ (
    .A(_17_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__nor2_1 _36_ (
    .A(_13_),
    .B(_28_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__xnor2_1 _37_ (
    .A(_14_),
    .B(_17_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__o21bai_1 _38_ (
    .A1(_13_),
    .A2(_19_),
    .B1_N(_28_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__a21oi_1 _39_ (
    .A1(_13_),
    .A2(_19_),
    .B1(_20_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__maj3_1 _40_ (
    .A(_13_),
    .B(_14_),
    .C(_18_),
    .X(_21_)
  );
  sky130_fd_sc_hd__xnor2_1 _41_ (
    .A(_17_),
    .B(_15_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__a21oi_1 _42_ (
    .A1(_21_),
    .A2(_22_),
    .B1(_28_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__o21a_1 _43_ (
    .A1(_21_),
    .A2(_22_),
    .B1(_23_),
    .X(_11_)
  );
  sky130_fd_sc_hd__or4_1 _44_ (
    .A(_13_),
    .B(_14_),
    .C(_17_),
    .D(_15_),
    .X(_24_)
  );
  sky130_fd_sc_hd__nand4_1 _45_ (
    .A(_13_),
    .B(_14_),
    .C(_17_),
    .D(_15_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__nand2_1 _46_ (
    .A(_24_),
    .B(_25_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__xnor2_1 _47_ (
    .A(_16_),
    .B(_26_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__nor2_1 _48_ (
    .A(_28_),
    .B(_27_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__dfxtp_1 _49_ (
    .CLK(clk),
    .D(_31_),
    .Q(count[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _50_ (
    .CLK(clk),
    .D(_32_),
    .Q(count[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _51_ (
    .CLK(clk),
    .D(_33_),
    .Q(count[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _52_ (
    .CLK(clk),
    .D(_34_),
    .Q(count[3])
  );
  assign _30_[0] = _29_[0];
  assign _13_ = count[0];
  assign _14_ = count[1];
  assign _17_ = ctrl;
  assign _15_ = count[2];
  assign _16_ = count[3];
  assign _28_ = reset;
  assign _31_ = _09_;
  assign _32_ = _10_;
  assign _33_ = _11_;
  assign _34_ = _12_;
endmodule
