#!/bin/bash

# Run Yosys with the provided yosys.tcl script in the background.
yosys -s yosys_run.ys

# Store the PID (Process ID) of the Yosys process
yosys_pid=$!

# Wait for Yosys to complete
wait $yosys_pid

# Create the "bidcounter_ff_1v95" directory within the "netlist" directory
mkdir -p "$(dirname "$0")/netlist/bidcounter_tt_100C_1v80"

# Assuming bidcounter_ff_1v95.v is generated by Yosys and you want to move it.
mv bidcounter_tt_100C_1v80.v "$(dirname "$0")/netlist/bidcounter_tt_100C_1v80/"

# Exit the script
exit

